package com.foodflow.service;

import com.foodflow.dto.RestaurantPatchRequest;
import com.foodflow.dto.RestaurantRequest;
import com.foodflow.dto.RestaurantResponse;
import com.foodflow.entity.Restaurant;
import com.foodflow.entity.Role;
import com.foodflow.entity.User;
import com.foodflow.exception.ApiException;
import com.foodflow.exception.ResourceNotFoundException;
import com.foodflow.repository.RestaurantRepository;
import com.foodflow.repository.UserRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class RestaurantServiceTest {

    @Mock
    private RestaurantRepository restaurantRepository;

    @Mock
    private UserRepository userRepository;

    @InjectMocks
    private RestaurantService restaurantService;

    private User sampleOwner;
    private Restaurant sampleRestaurant;

    @BeforeEach
    void setUp() {
        org.springframework.security.core.userdetails.User principal =
                new org.springframework.security.core.userdetails.User("chef_john", "pass", Collections.emptyList());
        UsernamePasswordAuthenticationToken auth =
                new UsernamePasswordAuthenticationToken(principal, null, Collections.emptyList());
        SecurityContextHolder.getContext().setAuthentication(auth);

        sampleOwner = User.builder()
                .id(1L)
                .username("chef_john")
                .email("john@foodflow.com")
                .role(Role.ROLE_USER)
                .build();

        sampleRestaurant = Restaurant.builder()
                .id(1L)
                .restaurantName("Green Bowl")
                .location("Saket, Delhi")
                .cuisine("Healthy, Continental")
                .rating(4.6)
                .owner(sampleOwner)
                .foodItems(new ArrayList<>())
                .build();
    }

    @AfterEach
    void tearDown() {
        SecurityContextHolder.clearContext();
    }

    @Test
    @DisplayName("Should retrieve all restaurants")
    void shouldGetAllRestaurants() {
        when(restaurantRepository.findAll()).thenReturn(List.of(sampleRestaurant));

        List<RestaurantResponse> result = restaurantService.getAllRestaurants();

        assertThat(result).hasSize(1);
        assertThat(result.get(0).getRestaurantName()).isEqualTo("Green Bowl");
    }

    @Test
    @DisplayName("Should retrieve restaurant by id")
    void shouldGetRestaurantById() {
        when(restaurantRepository.findById(1L)).thenReturn(Optional.of(sampleRestaurant));

        RestaurantResponse result = restaurantService.getRestaurantById(1L);

        assertThat(result).isNotNull();
        assertThat(result.getId()).isEqualTo(1L);
        assertThat(result.getRestaurantName()).isEqualTo("Green Bowl");
        assertThat(result.getOwnerUsername()).isEqualTo("chef_john");
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException when restaurant not found")
    void shouldThrowWhenRestaurantNotFound() {
        when(restaurantRepository.findById(99L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> restaurantService.getRestaurantById(99L))
                .isInstanceOf(ResourceNotFoundException.class);
    }

    @Test
    @DisplayName("Should create a restaurant with auto-generated ID and JWT owner")
    void shouldCreateRestaurantWithAutoGeneratedIdAndOwner() {
        RestaurantRequest request = RestaurantRequest.builder()
                .restaurantName("FoodFlow Kitchen")
                .location("Delhi")
                .cuisine("North Indian")
                .rating(4.5)
                .build();

        when(userRepository.findByUsername("chef_john")).thenReturn(Optional.of(sampleOwner));
        when(restaurantRepository.save(any(Restaurant.class))).thenAnswer(invocation -> {
            Restaurant r = invocation.getArgument(0);
            r.setId(10L);
            return r;
        });

        RestaurantResponse response = restaurantService.createRestaurant(request);

        assertThat(response).isNotNull();
        assertThat(response.getId()).isEqualTo(10L);
        assertThat(response.getRestaurantName()).isEqualTo("FoodFlow Kitchen");
        assertThat(response.getOwnerId()).isEqualTo(1L);
        assertThat(response.getOwnerUsername()).isEqualTo("chef_john");
        verify(restaurantRepository, times(1)).save(any(Restaurant.class));
    }

    @Test
    @DisplayName("Should PATCH single field (rating)")
    void shouldPatchSingleField() {
        RestaurantPatchRequest patch = RestaurantPatchRequest.builder()
                .rating(4.0)
                .build();

        when(restaurantRepository.findById(1L)).thenReturn(Optional.of(sampleRestaurant));
        when(restaurantRepository.save(any(Restaurant.class))).thenReturn(sampleRestaurant);

        RestaurantResponse response = restaurantService.patchRestaurant(1L, patch);

        assertThat(response).isNotNull();
        assertThat(sampleRestaurant.getRating()).isEqualTo(4.0);
        assertThat(sampleRestaurant.getRestaurantName()).isEqualTo("Green Bowl"); // unchanged
    }

    @Test
    @DisplayName("Should PATCH multiple fields (name and rating)")
    void shouldPatchMultipleFields() {
        RestaurantPatchRequest patch = RestaurantPatchRequest.builder()
                .restaurantName("Green Bowl Special")
                .rating(4.9)
                .build();

        when(restaurantRepository.findById(1L)).thenReturn(Optional.of(sampleRestaurant));
        when(restaurantRepository.save(any(Restaurant.class))).thenReturn(sampleRestaurant);

        RestaurantResponse response = restaurantService.patchRestaurant(1L, patch);

        assertThat(response).isNotNull();
        assertThat(sampleRestaurant.getRestaurantName()).isEqualTo("Green Bowl Special");
        assertThat(sampleRestaurant.getRating()).isEqualTo(4.9);
        assertThat(sampleRestaurant.getLocation()).isEqualTo("Saket, Delhi"); // unchanged
    }

    @Test
    @DisplayName("Should PATCH all editable fields")
    void shouldPatchAllFields() {
        RestaurantPatchRequest patch = RestaurantPatchRequest.builder()
                .restaurantName("New Name")
                .location("Gurgaon")
                .cuisine("Pan-Asian")
                .rating(4.7)
                .build();

        when(restaurantRepository.findById(1L)).thenReturn(Optional.of(sampleRestaurant));
        when(restaurantRepository.save(any(Restaurant.class))).thenReturn(sampleRestaurant);

        RestaurantResponse response = restaurantService.patchRestaurant(1L, patch);

        assertThat(response).isNotNull();
        assertThat(sampleRestaurant.getRestaurantName()).isEqualTo("New Name");
        assertThat(sampleRestaurant.getLocation()).isEqualTo("Gurgaon");
        assertThat(sampleRestaurant.getCuisine()).isEqualTo("Pan-Asian");
        assertThat(sampleRestaurant.getRating()).isEqualTo(4.7);
    }

    @Test
    @DisplayName("Should throw ApiException 400 when PATCH payload is empty {}")
    void shouldThrow400OnEmptyPatch() {
        RestaurantPatchRequest emptyPatch = RestaurantPatchRequest.builder().build();

        assertThatThrownBy(() -> restaurantService.patchRestaurant(1L, emptyPatch))
                .isInstanceOf(ApiException.class)
                .hasMessageContaining("cannot be empty");

        verify(restaurantRepository, never()).save(any(Restaurant.class));
    }

    @Test
    @DisplayName("Should throw ApiException 400 when PATCH rating is invalid")
    void shouldThrow400OnInvalidRating() {
        RestaurantPatchRequest invalidPatch = RestaurantPatchRequest.builder()
                .rating(6.5)
                .build();

        when(restaurantRepository.findById(1L)).thenReturn(Optional.of(sampleRestaurant));

        assertThatThrownBy(() -> restaurantService.patchRestaurant(1L, invalidPatch))
                .isInstanceOf(ApiException.class)
                .hasMessageContaining("Rating must be between 0.0 and 5.0");
    }

    @Test
    @DisplayName("Should throw ResourceNotFoundException when patching nonexistent restaurant")
    void shouldThrow404WhenPatchingNonexistent() {
        RestaurantPatchRequest patch = RestaurantPatchRequest.builder()
                .rating(4.0)
                .build();

        when(restaurantRepository.findById(999L)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> restaurantService.patchRestaurant(999L, patch))
                .isInstanceOf(ResourceNotFoundException.class);
    }
}
